### ISSUE TITLE
Provider: Error when trying to enable my account with MM on a testnet

### ISSUE THREAD

**Issue by facuspagnuolo** [aragon/court-dashboard#127]
I'm facing some kind of "an error has occurred while trying to enable your account, try a different provider" when clicking the "enable account" button using MetaMask if I was connected to one of the testnets. Maybe we should disable this functionality for testnets, or warn the user that the dashboard is not available for testnets yet

**Comment by sohkai** [comment]
This was most likely due to Metamask being on the wrong network at the time. An error is now displayed with #126.
