### ISSUE TITLE
Dispute: render agreement text along with evidence

### ISSUE THREAD

**Issue by sohkai** [aragon/court-dashboard#148]
If we know that the agreement text is renderable (e.g. is markdown), it would be nice to render it alongside the evidence to provide more context for jurors in the app itself.

**Comment by rperez89** [comment]
> If we know that the agreement text is renderable (e.g. is markdown), it would be nice to render it alongside the evidence to provide more context for jurors in the app itself.

Should it be displayed as an accordion also? i think that we might need some desings from @dizzypaty

**Comment by sohkai** [comment]
Yes, this is something we will need to consider designs for.

**Comment by sohkai** [comment]
Closing for now—we will re-evaluate if/when we will implement this!
