### ISSUE TITLE
Tasks: due date says "today" even though it's tomorrow

### ISSUE THREAD

**Issue by sohkai** [aragon/court-dashboard#181]
E.g. if you go to https://court.aragon.org/dashboard or https://court.aragon.org/tasks today, you'll see:

<img width="1121" alt="Screen Shot 2020-02-18 at 3 18 05 PM" src="https://user-images.githubusercontent.com/4166642/74744188-158c2480-5262-11ea-9892-eaee938f4bda.png">

There's more than one day remaining so it's a bit odd it says "today". Given that "today" is also very subjective, I wonder if it's better to say "in the next day" until we get closer, e.g. less than 12 hours (or we use the browser's local time zone to check if the end date is actually in the same day as the person)?

------

Spec:

- If end date is in the same day (as the browser's time zone), say "today"
- If end date is the next day, say "in the next day"
- Otherwise, say "in X days"

**Comment by rperez89** [comment]
Could we use this? https://day.js.org/docs/en/display/to

**Comment by sohkai** [comment]
I'd be against adding a dayjs plugin just to do this, especially since we only care about the granularity of a few hours (vs. say, years).
