### ISSUE TITLE
Duplicate evidence showing up sometimes

### ISSUE THREAD

**Issue by john-light** [aragon/court-dashboard#185]
There is a bug that shows duplicate evidence for some users some of the time:

<img width="745" alt="Screenshot_2020-02-18_at_19 34 58" src="https://user-images.githubusercontent.com/9424721/74774430-ae6e7000-5261-11ea-836b-14beaf3a8956.png">

**Comment by rperez89** [comment]
@john-light there is an [open pr](https://github.com/aragon/court-dashboard/pull/156) to fix this. Thanks!
