### ISSUE TITLE
"Learn more" in appeal confirmation window does not link anywhere

### ISSUE THREAD

**Issue by john-light** [aragon/court-dashboard#189]
See screenshot, where it says "Learn more" it looks like a link but doesn't go anywhere.

Also, the copy here is incorrect. There are two possible outcomes for the collateral if the confirming party is ruled against:

- The collateral could be redistributed to the appealing party, if the final ruling is in the appealing party's favor
- The collateral minus a fee could be returned to the confirming party, if the final ruling is in neither the appealing party nor the confirming party's favor (e.g. the appealing party proposes "In favor", the confirming party proposes "refuse to vote", and the final ruling is "against")

![Screenshot_2020-02-18 Aragon Court Dashboard(1)](https://user-images.githubusercontent.com/9424721/74784429-de277300-5275-11ea-89d2-5daaa48b877d.png)

**Comment by fabriziovigevani** [comment]
This is resolved in https://github.com/aragon/court-dashboard/pull/172
