### ISSUE TITLE
Dispute: juror drafting terms is hardcoded to three

### ISSUE THREAD

**Issue by sohkai** [aragon/court-dashboard#190]
This may be the case for the current mainnet environment, but shouldn't [this value](https://github.com/aragon/court-dashboard/blob/development/src/utils/dispute-utils.js#L11) be dynamic?

**Comment by fabriziovigevani** [comment]
Actually we should remove that value since the drafting can happen any time.

See https://github.com/aragon/court-dashboard/pull/82

**Comment by sohkai** [comment]
Ah, I don't know how I missed this after reading it so many times today. This is for the **draft**, not the **vote** or **reveal** phases 🤦‍♂️.

Was this intended to keep the draft button disabled for 3 terms so a bot could run it?
