### ISSUE TITLE
"Withdraw" button does not work

### ISSUE THREAD

**Issue by john-light** [aragon/court-dashboard#215]
After de-activating ANJ and waiting the necessary term period, I try to click "Withdraw" and nothing happens. Other users have reported the error message `JR_NOT_ENOUGH_AVAILABLE_BALANCE`.

**Comment by fabriziovigevani** [comment]
Yes we have seen this issue when monitoring transactions. This is mostly due to the court being out of sync when jurors want to withdraw (withdrawing ANJ requires that the court is synced at the current term). We will have this week the activity panel implemented and also hopefully the signer panel which will give more context on this types of errors.

**Comment by john-light** [comment]
@fabriziovigevani is there any fallback that users can rely on in cases when "the court" (I assume you mean the Ethereum node the court dashboard relies on) is out of sync? not being able to withdraw is a pretty serious problem to fix.

**Comment by fabriziovigevani** [comment]
By out of sync i mean the court term itself. Each court term lasts 8 hours and each time there's a new term, the court should be transitioned to that term (This is achieved by calling a function `heartbeat` on the court contract). Some ANJ actions like `Activate` and `Withdraw` try to sync the court if it's out of sync by 1 term but `withdraw` only executes if the court is synced and there are no required term transitions to be made. 

Spoke with @sohkai and the service that automatically syncs the court was down apparently but it's now back up. We are planning to create a Clock module where it tells users whether the court term is out of sync or not and give the chance to sync it in the case it's not.

**Comment by sohkai** [comment]
The automated service for heartbeats is now up and running, but it runs fairly infrequently (and in general, it is difficult to ensure we transition the court's term immediately when it can).

@fabriziovigevani Does the balance module currently assume that the term is transitioned based on the time? Wondering if we could avoid transactions failing if we only increase how much a user can withdraw after we know the heartbeat has been triggered.

**Comment by fabriziovigevani** [comment]
Yes, it currently assumes that the term is synced. 

> We are planning to create a Clock module where it tells users whether the court term is out of sync or not and give the chance to sync it in the case it's not.

Next i plan to work on this for which i have already an initial draft. 

> Wondering if we could avoid transactions failing if we only increase how much a user can withdraw after we know the heartbeat has been triggered.

And 'll work on this logic as well.

**Comment by sohkai** [comment]
We have mitigated this issue with the clock module and will close this issue.

We wait until we have the multi-transaction experience to fully solve all heartbeat issues by detecting when we need to force the user into triggering it.
