### ISSUE TITLE
Updates for subgraph

### ISSUE THREAD

**Issue by sohkai** [aragon/court-dashboard#247]
The subgraph has changed a bit and has renamings (see https://github.com/aragon/court-subgraph/pull/45).

We should update the any queries or schemas we use in the dashboard based on this, and improve the Court stats.

**Comment by fabriziovigevani** [comment]
Potential query attributes we need to update:

- Balances: 
    - `movements` => `anjMovements` 
    - `treasuryTokens` => `treasuryBalances`

Will be updating here for new ones.

**Comment by rperez89** [comment]
awsome thanks fabri!

**Comment by sohkai** [comment]
Closed by https://github.com/aragon/court-dashboard/pull/248.
