### ISSUE TITLE
Not running locally

### ISSUE THREAD

**Issue by abhinav-anshul** [aragon/court-dashboard#283]
The `npm start` or `yarn start` is failing to run this project locally on windows operating system. It logs the following error 

`'REACT_APP_BUILD' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by sohkai** [comment]
Ah, cc @fabriziovigevani @rperez89 we should use something like [`cross-env`](https://www.npmjs.com/package/cross-env) when defining env vars in the npm scripts.

**Comment by abhinav-anshul** [comment]
It is a development issue for windows platform.

1) To run it locally, remove the `REACT_APP_BUILD=$(git log --pretty=format:'%h' -n 1)` from the start script from `package.json` file
2) There is an eslint issue as well because the `linebreak-style` has been configured only for Unix. To resolve, please include `"linebreak-style": 0` instead of `"linebreak-style": [ "error", "unix"]`

**Comment by fabriziovigevani** [comment]
Hey thanks for reporting this. Addressed the issues at https://github.com/aragon/court-dashboard/pull/284

Re `eslint`, added a git attribute so git doesn't update your files with CRLF when checking out.
