### ISSUE TITLE
Request: add favicon

### ISSUE THREAD

**Issue by Evalir** [aragon/court-dashboard#309]
We seem to not have a favicon for the Court's dashboard. :) Should we design a new one, or just add the ANJ logo (this might clash with anj.aragon.orgr and convert.aragon.org)?

**Comment by sohkai** [comment]
This should be the favicon: https://github.com/aragon/court-dashboard/blob/development/public/icon.png.

If you're not seeing it, your privacy blocker / etc. may be blocking it.

**Comment by Evalir** [comment]
Ah interesting, it doesn't load with Brave at all for me.

**Comment by fabriziovigevani** [comment]
Are you still having issues visualizing it @Evalir ?

I'm using Brave and can see it no problem.

**Comment by Evalir** [comment]
Yep! Can see it now, seems this was on my side. Will close this.
