### ISSUE TITLE
LocalIdentityBadge: deprecate here

### ISSUE THREAD

**Issue by sohkai** [aragon/court-dashboard#312]
Could we rename `LocalIdentityBadge` to just `IdentityBadge`?

The `Local` bit is not needed here as we don't apply labels, and all the code for the custom Popovers / etc. aren't used AFAIK.

**Comment by fabriziovigevani** [comment]
Sure, i think this sticked from the very first iteration of a demo where we copied it from one of the apps and never did a proper cleaning.
