### ISSUE TITLE
"Status" column seems redundant

### ISSUE THREAD

**Issue by john-light** [aragon/court-dashboard#319]
Noticed that the Status column says "due in 2 days" while the due date column is right next to it and also says 1 day and 7 hours... contradictory no?

It also seems that the Status column only has two states: "open" and not visible at all, because the task has been done or is past due.

Proposal: I think the Status column here is redundant and probably unnecessary. The due date already has its own column, and if a task is "open" we can just show it on this tab, and if it's not open then we don't show it on this tab, so there is no need for a new column just to say that the task is "open".

Please correct me if I am wrong about anything here :) 

https://court.aragon.org/tasks

![Screenshot_2020-05-12 Aragon Court Dashboard(1)](https://user-images.githubusercontent.com/9424721/81757341-97b86d80-948c-11ea-90d3-374dbb56973a.png)

**Comment by sohkai** [comment]
Hmm yes, perhaps we could remove the time component out of the "status", so it just shows "Open", and we could also change the "Due date" label to be "Due in"?

cc @dizzypaty

**Comment by john-light** [comment]
Isn't the "Status" column redundant anyways since if the task is visible then the implication is that it is "open"? We don't seem to show a "Status: Done" state, for example.

**Comment by fabriziovigevani** [comment]
Yes, currently is redundant as we only are showing `open` tasks. This came from a first implementation where we were going to have past tasks as well but we ended up not implementing it for the first iteration. 
We could either drop this column for now or consider adding past tasks.

**Comment by john-light** [comment]
Personally, I don't see much value in showing past tasks. Just more stuff to load. But that's just me!

**Comment by john-light** [comment]
Related confusing thing: I was drafted for a case, voted, and still the `My Tasks` tab says "you have not been drafted to arbitrate a dispute yet" which just isn't true!

![Screenshot_2020-05-20 Aragon Court Dashboard(14)](https://user-images.githubusercontent.com/9424721/82498985-dcf92280-9abe-11ea-892a-9835cfe14717.png)

![Screenshot_2020-05-20 Aragon Court Dashboard(15)](https://user-images.githubusercontent.com/9424721/82499002-e1bdd680-9abe-11ea-8e07-482135451c7f.png)

**Comment by fabriziovigevani** [comment]
I think we could change the  `Due date` for `Due in` as suggested by @sohkai and remove the status column for now? If we end up adding past tasks we can consider re adding this column.

**Comment by sohkai** [comment]
Agreed; we have done this for the "due task" emails as well.
