### ISSUE TITLE
Bug: Unable to set custom Ethereum node

### ISSUE THREAD

**Issue by macor161** [aragon/court-dashboard#322]
Setting an infura URL(`https://mainnet.infura.io/v3/...`) as the Ethereum node results in the following error:
```
Node must be connected to mainnet
```
Also had reports that setting a local geth node URL returns :
```
Could not connect to node
```

**Comment by rperez89** [comment]
ah yes, for some reason `networkType.name` on Ethers for mainet is called `homestead` not sure why, should be fixed with https://github.com/aragon/court-dashboard/pull/277

**Comment by rperez89** [comment]
@macor161 just merged, let me know if is working for you

**Comment by sohkai** [comment]
> ah yes, for some reason networkType.name on Ethers for mainet is called homestead not sure why

Ah yes, this is an odd piece of history. Homestead was the first "official" launch name of Ethereum mainnet and is sometimes used to refer to it.

**Comment by macor161** [comment]
Works perfectly now! Thanks @rperez89!
