### ISSUE TITLE
"My Tasks" tab says I haven't been drafted yet even though I have

### ISSUE THREAD

**Issue by john-light** [aragon/court-dashboard#339]
I was drafted for a case, voted successfully, went to the `My Tasks` tab and it says I have not been drafted to arbitrate a case yet, which just isn't true.

![Screenshot_2020-05-20 Aragon Court Dashboard(14)](https://user-images.githubusercontent.com/9424721/82499170-3a8d6f00-9abf-11ea-95d1-21c5983ccf6d.png)

![Screenshot_2020-05-20 Aragon Court Dashboard(15)](https://user-images.githubusercontent.com/9424721/82499195-424d1380-9abf-11ea-9c57-2da057e860d0.png)

**Comment by rperez89** [comment]
ahh good catch, that is because once you execute the task is not open anymore and we are showing the same empty page, should we show something like you have no open tasks? or something like that?

**Comment by rperez89** [comment]
maybe we should remove that msg about if you were drafted or not, i mean don't show that msg never and just say that you have no open tasks

**Comment by john-light** [comment]
I think just saying "You have no open tasks right now" should be fine. Also, while we're looking at this section, the fact that "ANJ you activate" is blue text but not a hyperlink is also kind of confusing.

**Comment by sohkai** [comment]
I think this is a problem we have across the board (e.g. in home) with the empty states—they all assume you're a new juror who has never been involved.

How easy is it for us to detect that the juror was previously drafted?

**Comment by john-light** [comment]
> How easy is it for us to detect that the juror was previously drafted to switch to a different empty state?

Seems overly complicated when we could just say something generic like "You have no open tasks right now", no? What is the benefit to customizing this just for new jurors?

**Comment by sohkai** [comment]
On the flipside, it seems a bit weird to say that to someone who just joined as a juror or has never been drafted.

**Comment by rperez89** [comment]
i think that i am also up to just say "You have no open tasks right now" because at the end of the day you are checking the tasks screen, makes sense to see that msg if you don't have open tasks

**Comment by john-light** [comment]
"You have no open tasks right now. You will receive tasks to complete when you are drafted for a dispute."

Works for new and previously-drafted jurors alike, and shares enough context to set expectations for new jurors. What do you think @sohkai @rperez89 ?

**Comment by rperez89** [comment]
I

> "You have no open tasks right now. You will receive tasks to complete when you are drafted for a dispute."
> 
> Works for new and previously-drafted jurors alike, and shares enough context to set expectations for new jurors. What do you think @sohkai @rperez89 ?

I am ok with that! let me know and i can fix it ! @sohkai

**Comment by sohkai** [comment]
Sounds good to me!
