### ISSUE TITLE
Unable to prematurely dismiss onboarding modal

### ISSUE THREAD

**Issue by andy-hook** [aragon/court-dashboard#349]
![image](https://user-images.githubusercontent.com/11708259/82878554-8c0c8280-9f33-11ea-958c-d5dbbc85d435.png)

Hi folks, I spotted a minor defect with this modal. I'm unable to dismiss the flow by clicking the background scrim or the close button in the top right. The modal also sits vertically off-center in Safari.

**Comment by fabriziovigevani** [comment]
Hmm i think it's not supposed to be closable so we should definitely remove the cross icon @rperez89 ?

> The modal also sits vertically off-center in Safari.

Will look into it 👍

**Comment by sohkai** [comment]
Yes, it's not supposed to be closable.

I have the feeling we've tackled this issue a few times, to avoid throwing react errors, but perhaps we've forgotten to remove the cross over time 😅

**Comment by Evalir** [comment]
Done in #358 .
