### ISSUE TITLE
Overview: Buy/Sell ANJ module

### ISSUE THREAD

**Issue by facuspagnuolo** [aragon/court-dashboard#4]
The idea of this module is to allow buying/selling ANJ tokens to the jurors. It is not defined yet, but it will probably be related to the jurors [onboarding flow](https://anj.aragon.org/) to ensure consistency

**Comment by sohkai** [comment]
Closing for now; as the converter is getting more complicated due to the bonding curve backend, we will likely just keep linking to it instead.
