### ISSUE TITLE
Accountancy: History of treasury movements

### ISSUE THREAD

**Issue by facuspagnuolo** [aragon/court-dashboard#5]
This section should be perceived as a detailed version of the [balances module](https://github.com/aragon/court-dashboard/issues/1). The idea is to show accounting historic information of how the different balances and amounts of a juror have been moved along the court lifecycle. At the end of the day, jurors must have a way to match incomes and outcomes.

**Comment by sohkai** [comment]
Closing for now; will re-open once we are ready to begin.
