### ISSUE TITLE
Notification preferences

### ISSUE THREAD

**Issue by facuspagnuolo** [aragon/court-dashboard#6]
Integrate into the backend notifications service.

Architecture and authentication design, along with REST flow charts: https://www.notion.so/aragon/Notifications-architecture-design-63671829a127407b823c3dbd2163eb96#2d593509406c4594b1aa01d8eb97bbc5

Designs: https://www.figma.com/file/IdVA6iMn0cWLV5imylwEUP/%E2%9A%96%EF%B8%8F-Court-Dashboard-Master?node-id=4980%3A5415

**Comment by sohkai** [comment]
Closing for now to design and scope; will re-open once we're ready to work on this.

**Comment by sohkai** [comment]
We are beginning to work on the backend component; frontend can start once we've finalized a REST contract.

**Comment by sohkai** [comment]
Closing with #318.
